### ISSUE TITLE
contract generator

### ISSUE THREAD

**Issue by ronerlih** [zkMaps/zkMaps#21]
### contract generator

Enable users to create verifier contracts on demand for EVM compatible blockchains.

controller to receive points and generate contract OR verification interface method TBD
[notion ref](https://www.notion.so/Contract-generator-a9475cee271e4f1b96e79055f0427ffa)

criteria
- [ ] endpoint to recive location range
- [ ] auto generate contract
- [ ] auto deploy contract

##. Next steps
- polygon input coordiates #28

**Comment by 0xPetra** [comment]
Should we close this now that we're generating generic contracts?

**Comment by BlakeMScurr** [comment]
Yup, agreed!
